### ISSUE TITLE
Release the damn thing before I do

### ISSUE THREAD

**Issue by iamgreaser** [ChenThread/ice#1]
As in, I'm just going to dump the optimised v7 C version (not to be confused with the other v7 we've been talking about lately).

Cheers.

**Comment by asiekierka** [comment]
Please give me time for my winter break to start. Thank you.

(Three days)

**Comment by asiekierka** [comment]
https://github.com/ChenThread/ice/commit/2f5d4065e21512944867e9acbecf988d6ea1af14
